# Generated by Django 5.2.6 on 2025-10-01 00:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
